version: '3.8'
services:
  frontend:
    image: my-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: my-backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=harshsql
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=harshsql
      - MYSQL_DATABASE=testdb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
